---
title: "Informe M8R2"
author: "Gabriel Parada"
date: "2025-08-08"
output: 
    html_document:
    toc: true
    number_sections: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning =  F, message = F, fig.width = 8, fig.height = 8)

```

# Paquetes

```{r}
library(knitr)
library(tidyr)
library(plotly)
library(readxl)
library(dplyr)
library(ggplot2)
library(here)
library(sf)
library(ggplot2)
library(plotly)
library(dplyr)
library(readr)
library(DT)

```

# Cargar los datos
```{r}
df_LA_GDP <- read.csv(here("Datos", "df_LA_GDP.csv"))

```

# Introducción

```{r , echo=FALSE}
#Estadísticas descriptivas del dataset original
# summary(df_LA_GDP$`life_expectancy`)
# 
# #Encontrar los outliers
# outliersPorA <- df_LA_GDP %>%
#   group_by(year) %>%
#   mutate(
#     Q1 = quantile(life_expectancy, 0.25, na.rm = TRUE),
#     Q3 = quantile(life_expectancy, 0.75, na.rm = TRUE),
#     IQR_value = IQR(life_expectancy, na.rm = TRUE),
#     lower = Q1 - 1.5 * IQR_value,
#     upper = Q3 + 1.5 * IQR_value,
#     is_outlier = life_expectancy < lower | life_expectancy > upper
#   ) %>%
#   filter(is_outlier == TRUE)
# 

```

```{r}

# ggplot(df_LA_GDP, aes(x = life_expectancy)) +
#   geom_histogram(aes(y = ..density..), fill = "lightblue", bins = 30, color = "white") +
#   geom_density(color = "red", size = 1.2) +
#   labs(title = "Esperanza de vida en Suramérica periodo 1800 - 2100",
#        x = "Esperanza de Vida en años",
#        y = "Densidad") +
#     scale_x_continuous(breaks = seq(0,100, by = 5))


```
```{r}

 # ggplot(mediaSur, aes(x = year, y = life_expectancy, color = life_expectancy)) +
 #  geom_line(size = 1.2) +
 #     geom_line() +
 #     facet_wrap(~ name) +
 #     labs(title = "Esperanza de vida por año", x = "Año", y = "Esperanza de Vida (años)") +
 #    theme_minimal()

```
```{r}

# colores = c("#1F77B4", "#FF7F0E", "#2CA02C", "#D62728", "#9467BD", "#7F7F7F", "#BCBD22", "#17BECF", "#0055A4", "#006400")
# 
# 
# ggplot(dfLAmerica, aes(x = name, y = life_expectancy)) +
#   geom_boxplot(fill = colores) +
#   labs(title = "Esperanza de vida",
#        y = "Esperanza de vida", x = "País") +
#   theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}

# Gráfico de líneas para las variables

# Formato largo del df
# df_long <- df_LA_GDP %>%
#   pivot_longer(cols = c(GDP),
#                names_to = "variable",
#                values_to = "value")
# 
# df_summary <- df_long %>%
#   group_by(year, variable) %>%
#   summarise(mean_value = mean(value, na.rm = TRUE), .groups = "drop")
# 
# ggplot(df_summary, aes(x = year, y = mean_value, color = variable)) +
#   geom_line(size = 1.2) +
#   labs(
#     title = "Media GDP per capita Suramérica (1800–2100)",
#     x = "Año",
#     y = "GDP per cápita ($)",
#     color = "Variable"
#   ) +
#   theme_minimal()

```
